### ISSUE TITLE
who writes README ?

### ISSUE THREAD

**Issue by i13302** [i13302/learn#5]
@gacky35 ? @unomitsu ?

**Comment by i13302** [comment]
i write readme now.

**Comment by unomitsu** [comment]
● Windows
Run in Windows PowerShell

1. Move to the folder where the Dockerfile is
`cd `

2. Execute the command in build.sh
`docker build . -t superml`

3. Fixed command in start.sh, execute the command
docker run -it --rm --publish 8888:8888 --volume **\`PWD\`**/work:/home/jovyan/work/ superml
　↓
`docker run -it --rm --publish 8888:8888 --volume ${PWD}/work:/home/jovyan/work/ superml `

4. Open jupyter notebook in browser
`localhost:8888`

**Comment by i13302** [comment]
build.sh
```
#/bin/bash

docker build . -t superml
```

start.sh
```
#!/bin/bash

docker run -it --rm --publish 8888:8888 --volume $(pwd)/work:/home/jovyan/work/ superml 
```
